#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
# Publish All In on itch.io (#71). Run from the repo root after
# `cargo build --release && tools/package.sh`. Each stage opens the page it
# needs and says what to click; nothing here is irreversible until stage 6.

TOTAL_STAGES=6
BUTLER="tools/butler"

banner "All In → itch.io"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the project"
say "A draft project first; it goes public in the last stage."
open_url "https://itch.io/game/new"
step "Title: All In."
step "Classification: Game.  Kind of project: Downloadable."
step "Pricing: No payments."
step "Visibility: Draft (bottom of the form)."
step "Save. The page's URL is https://<you>.itch.io/<slug>."
ask ITCH_USER "Your itch.io username (the <you> part):"
ask ITCH_GAME "The game's URL slug (the <slug> part, probably all-in):"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Install butler"
say "butler is itch's upload tool. It goes in tools/ and is git-ignored."
if [ -x "$BUTLER" ]; then
  note "tools/butler is already here; skipping the download."
else
  step "Downloads linux-amd64 from itch's own release channel (broth.itch.zone)."
  if confirm "Download butler now?"; then
    curl -L "https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default" -o tools/butler.zip
    python3 -c "import zipfile; zipfile.ZipFile('tools/butler.zip').extract('butler','tools')"
    chmod +x "$BUTLER" && rm -f tools/butler.zip
    "$BUTLER" --version
  else
    warn "Install butler by hand (https://itch.io/docs/butler/installing.html) and rerun."
    exit 1
  fi
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Log in"
say "butler opens a browser; approve it there and come back."
"$BUTLER" login
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Push the Linux build"
[ -d dist/all-in-linux ] || { warn "dist/all-in-linux is missing: run tools/package.sh first."; exit 1; }
say "Pushing the folder, not the zip: itch diffs future pushes against it."
step "Channel 'linux' tags the upload as a Linux download automatically."
if confirm "Push dist/all-in-linux to $ITCH_USER/$ITCH_GAME:linux?"; then
  "$BUTLER" push dist/all-in-linux "$ITCH_USER/$ITCH_GAME:linux" --userversion 0.1.0
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Page content"
open_url "https://itch.io/game/edit/$ITCH_GAME"
note "If that URL 404s, open your dashboard and click Edit on All In."
step "Description: paste docs/itch-page.md (it's already in itch's markdown)."
step "Cover image: itch wants 630×500. assets/icon.png is square; letterbox it, or"
step "  crop assets/backdrops/title.png to 630×500."
step "Screenshots: three, taken from the game: the table mid-hand, the House"
step "  with 'House Edge ?', the Opening. Any screenshot tool; 1920×1080 is fine."
step "Uploads: the linux channel from stage 4 should be listed. Tick"
step "  'This file will be played in the browser' OFF; leave platform Linux."
step "Genre: Card Game. Tags: roguelike, card-game, casino, noir, bevy, rust."
step "Save."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Publish"
warn "This is the public step."
step "Same edit page, bottom: Visibility → Public. Save."
if confirm "Published?"; then
  ask ITCH_URL "Paste the public URL (https://$ITCH_USER.itch.io/$ITCH_GAME):"
  printf '%s\n' "$ITCH_URL" > dist/ITCH_URL
  say "Written to dist/ITCH_URL. Tell Claude and it goes into docs/pitch.md and the map."
fi

finish
